Fix summary_resources when affected resources are None
Fixes a bug:
```
Traceback (most recent call last):
  File "/home/runner/.local/bin/ih-plan", line 8, in <module>
    sys.exit(ih_plan())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in
__call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in
main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in
invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in
invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in
new_func
    return f(get_current_context(), *args, **kwargs)
  File
"/home/runner/.local/lib/python3.10/site-packages/infrahouse_toolkit/cli/ih_plan/cmd_publish/__init__.py",
line 70, in cmd_publish
    pull_request.publish_comment(status.comment)
  File
"/home/runner/.local/lib/python3.10/site-packages/infrahouse_toolkit/terraform/status.py",
line 76, in comment
    + (f"## Affected resources by action\n\n{self.summary_resources}\n"
if self.affected_resources else "")
  File
"/home/runner/.local/lib/python3.10/site-packages/infrahouse_toolkit/terraform/status.py",
line 125, in summary_resources
    [["🟢", f"`{field}`"] for field in self.affected_resources.add]
TypeError: 'NoneType' object is not iterable
```