Pin elasticsearch to 8.12.0
Something broke in 8.13.0

```
2024-03-28T02:43:34.7850120Z
infrahouse_toolkit/cli/ih_elastic/cmd_snapshots/cmd_create_repository/__init__.py:25:4:
E1123: Unexpected keyword argument 'settings' in method call
(unexpected-keyword-arg)
2024-03-28T02:43:34.7854367Z
infrahouse_toolkit/cli/ih_elastic/cmd_snapshots/cmd_create_repository/__init__.py:25:4:
E1123: Unexpected keyword argument 'type' in method call
(unexpected-keyword-arg)
```

I get it, semantic versioning is not for everybody.