Fix comment when the plan result is None:
Fixes a bug:
```
Traceback (most recent call last):
  File "/home/runner/.local/bin/ih-plan", line 8, in <module>
    sys.exit(ih_plan())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in
__call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in
main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in
invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in
invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in
new_func
    return f(get_current_context(), *args, **kwargs)
  File
"/home/runner/.local/lib/python3.10/site-packages/infrahouse_toolkit/cli/ih_plan/cmd_publish/__init__.py",
line 70, in cmd_publish
    pull_request.publish_comment(status.comment)
  File
"/home/runner/.local/lib/python3.10/site-packages/infrahouse_toolkit/terraform/status.py",
line 75, in comment
    + f"## Affected resources counts\n\n{self.summary_counts}\n"
  File
"/home/runner/.local/lib/python3.10/site-packages/infrahouse_toolkit/terraform/status.py",
line 110, in summary_counts
    f"{'🟢' if self.success and self.add > 0 else ''} Add",
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

It happens when the plan has no changes.